============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
From https://github.com/JuliusHuizing/master-thesis-ds
   ae41169..1cd5a9d  main       -> origin/main
Updating ae41169..1cd5a9d
Fast-forward
 pipeline.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
2024-05-06 12:45:38,972 - INFO - Loading configuration...
2024-05-06 12:45:38,975 - INFO - ✅ Configuration loaded.
2024-05-06 12:45:38,975 - INFO - Loading paths...
2024-05-06 12:45:38,975 - INFO - ✅ Paths loaded.
2024-05-06 12:45:38,975 - INFO - Initializing preprocessing pipeline...
2024-05-06 12:45:38,976 - INFO - Running preprocessing pipeline...
2024-05-06 12:45:43,129 - ERROR - ❌ Subprocess error with non-zero exit status 2
2024-05-06 12:45:43,129 - ERROR - Standard error of the subprocess: usage: process.py [-h] [--model MODEL] [--size SIZE]
                  [--border_ratio BORDER_RATIO] [--recenter RECENTER]
                  path
process.py: error: the following arguments are required: path

Traceback (most recent call last):
  File "pipeline.py", line 44, in <module>
    result = subprocess.run(command, check=True, text=True, capture_output=True)
  File "/home/jhuizing/.conda/envs/dreamgaussianV2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'repos/dreamgaussian/process.py', '--size', '256', '--border_ratio', '0.2', '--recenter', 'True']' returned non-zero exit status 2.

JOB STATISTICS
==============
Job ID: 6159165
Cluster: snellius
User/Group: jhuizing/jhuizing
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 00:04:30 core-walltime
Job Wall-clock time: 00:00:15
Memory Utilized: 0.00 MB (estimated maximum)
Memory Efficiency: 0.00% of 120.00 GB (120.00 GB/node)
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
